# Generated by Django 3.0.5 on 2020-05-08 21:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post_questions', '0003_auto_20200508_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquestion',
            name='create_date',
        ),
        migrations.AddField(
            model_name='postquestion',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 8, 21, 18, 24, 548781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 5, 8, 21, 18, 24, 549784, tzinfo=utc)),
        ),
    ]
