# Generated by Django 3.0.5 on 2020-05-09 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post_questions', '0004_auto_20200508_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='postquestion',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
