# Generated by Django 3.0.5 on 2020-05-09 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_questions', '0005_auto_20200509_0059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostQuestion',
            new_name='Post',
        ),
    ]
